### PR TITLE
Fixes 2fa

### LINKED ISSUE #129: 2FA setup not working
After generating the QR code to activate the 2FA, the TOTP codes are not accepted by the system, indicated by the following error:
image

### PR DESCRIPTION
**Pull request by julianochoi**
## Description
[Provide a brief description of the changes made in this pull request.]

## Related Issue
[Closes/Fixes/Resolves #[issue number]: Describe the related issue that this PR addresses.]
Closes #129

### CODE REVIEW

File: backend/src/interceptors/remove-users-fields/remove-users-fields.interceptor.ts [hunk 1]
```diff
@@ -18,7 +18,8 @@ export class RemoveUsersFieldsInterceptor implements NestInterceptor {
         }
         delete user.refreshToken;
         delete user.mfaSecret;
-        delete user.mfaEnabled;
+        // NOTE Is it necessary to remove mfaEnabled?
```
Comment (julianochoi) [inline backend/src/interceptors/remove-users-fields/remove-users-fields.interceptor.ts:21]: Is it necessary to delete mfaEnabled from user requests?
If this is a security issue, we will need to change part of the 2FA architecture because this is currently public in the payload part of the JWT.

Comment (iaurg) [reply backend/src/interceptors/remove-users-fields/remove-users-fields.interceptor.ts:21]: Well, I think that if we just send whether it is enabled or not, it's not a problem. Only the secret is dangerous here.

**Review by vcwild — APPROVED** [review]
image
